### ISSUE TITLE
问题，如何动态渲染data？

### ISSUE THREAD

**Issue by newlife** [vue-bulma/handsontable#2]
从后端请求的数据无法绑定到data上，请问该如何处理？

**Comment by shuyue426** [comment]
`<div class="handsontable"></div>`,
这个模版中没有包含双向绑定的模型，改变了data无法触发组件再次渲染，进不了update生命钩子。
我改了下，加了个title：

`<div>`
    `<div>{{title}}</div>`
   ` <div class="handsontable"></div>`
 ` </div>`

`title:{`
      `type: String,`
      `required: true`
 `}`
  
`<handsontable :settings="{data:htdata}" :title="title"></handsontable>`
           
在请求事件中设置：this.title="title1";这样这个组件就能刷新了。

1）不知道作者有什么更好的解决？
2）这个title在页面上居然不显示，还是只有handsontable，晚点研究看看。

**Comment by okjesse** [comment]
`  watch: {
    data: function (newData) {
      this.settings.data = newData;
      this.table.loadData(this.settings.data);
    }
  },`
增加这个在Handsontable.vue里就可以了

**Comment by luventa** [comment]
楼上正解 👍
